#!/bin/bash
function usage
{
    echo "usage: labRunning [-h]
                                      --region [-r] 	us-east-1 - If not specified all regions will be checked
                                                        If start or end are not specified it will run to the end
"
}

while [ "$1" != "" ]; do
    case $1 in
        -r | --region )         shift
                                REGIONS=$1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
    esac
    shift
done


if [ -z "$REGIONS" ]
then
   REGIONS=($(aws ec2 describe-regions --query Regions[*].RegionName --output text --profile cliaccount))
fi

NumberOfAccounts=(1 2 3 4)

for accounts in "${NumberOfAccounts[@]}"
#for ((accounts=01;accounts<=count;accounts++))
#for accounts in $(eval echo {$begin..$count})
do
   profile="AVDev$accounts"
   echo $profile
   users=($(aws iam list-users --output text --query 'Users[*].UserName' --profile $profile))
   if [ ! -z "$users" ]
   then
      printf "Users : "
      aws iam list-users --output text --query 'Users[*].UserName' --profile $profile | tr -d "\n"
      printf "\n"
   fi
   
   #ARRAY=($(aws ec2 describe-regions --query Regions[*].RegionName --output text --profile $profile))
   for region in "${REGIONS[@]}"
   do
      aws configure set region $region --profile $profile
      stacks=($(aws cloudformation describe-stacks --query Stacks[*].StackName --output text --profile $profile))
      if [ ! -z "$stacks" ]
      then
         printf "\n$profile $region Stacks : "
         for stack in "${stacks[*]}"
         do
            printf "$stack"
         done
      fi
      instances=($(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[Tags[?Key==`Name`].Value]' --output text --profile $profile))
      #instances=($(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[Tags[?Key==`Name`].Value,State.Name]' --output text --profile $profile))
      if [ ! -z "$instances" ]
      then
         printf "\n$profile $region Instances : "
         for instance in "${instances[*]}"
         do
            printf "$instance"
         done
         printf "\n"
      fi
      printf "."
   done
printf "\n\n"
done

