#!/bin/bash
# If we haven't used a subOrg in a while it's token may expire. Running this will refresh all tokens
connect () {

accountName=$1
accountID=$2

echo "$accountName has the ID $accountID"
role="OrganizationAccountAccessRole"
aws sts assume-role --role-arn arn:aws:iam::$accountID:role/$role --role-session-name $accountName
aws configure set region us-east-1 --profile $accountName
aws configure set role_arn arn:aws:iam::$accountID:role/$role --profile $accountName
aws configure set source_profile default --profile $accountName
}

date

accArray=($(aws organizations list-accounts-for-parent --parent-id ou-yus6-1nrdvs4m --output text --query 'Accounts[*].[Name,Id]' | sort -V))
arraySize=${#accArray[@]}

echo "[default]
output = json
region = us-east-1
role_arn = arn:aws:iam::745499864989:role/AVOrgCreatorRole
credential_source  = Ec2InstanceMetadata" > ~/.aws/config

i=0
while [ $i -lt $arraySize ]
do
   j=$[$i+1]
   connect ${accArray[$i]} ${accArray[$j]}
   i=$[$i+2]
done

# Repeat for AVDev orgs
devArray=($(aws organizations list-accounts-for-parent --parent-id ou-yus6-erm3u7s2 --output text --query 'Accounts[*].[Name,Id]' | sort -V))
arraySize=${#devArray[@]}

i=0
while [ $i -lt $arraySize ]
do
   j=$[$i+1]
   connect ${devArray[$i]} ${devArray[$j]}
   i=$[$i+2]
done
